document.querySelector("#kfclogo").addEventListener("click", function(event){
    window.location.href="https://online.kfc.co.in/";
});
document.querySelector("#menu").addEventListener("click",function(){
    window.location.href="https://online.kfc.co.in/";
});
document.querySelector("#orderlook").addEventListener("click", function(){ 
    document.querySelector(".popup1").classList.add("active");
});
document.querySelector(".close_button").addEventListener("click", function(){ 
    document.querySelector(".popup1").classList.remove("active");
});
document.querySelector("#giftcard").addEventListener("click",function(){
    window.location.href="gift.html";
});
document.querySelector("#gethelp").addEventListener("click",function(){
    window.location.href="help.html";
});
document.querySelector("#contactus").addEventListener("click",function(){
    window.location.href="contactus.html";
});
document.querySelector("#terms").addEventListener("click",function(){
    window.location.href="terms.html";
});
document.querySelector("#privacypolicy").addEventListener("click",function(){
    window.location.href="Privacy.html";
});
document.querySelector("#disclaimer").addEventListener("click",function(){
    window.location.href="disclaimer.html";
});
document.querySelector("#caution").addEventListener("click",function(){
    window.location.href="caution.html";
});
document.querySelector("#privacy").addEventListener("click",function(){
    window.location.href="Privacy.html";
});
document.querySelector("#about").addEventListener("click",function(){
    window.location.href="about.html";
});
document.querySelector("#care").addEventListener("click",function(){
    window.location.href="care.html";
});
document.querySelector("#careers").addEventListener("click",function(){
    window.location.href="careers.html";
});
document.querySelector("#goldenpast").addEventListener("click",function(){
    window.location.href="golden.html";
});
document.querySelector("#logo").addEventListener("click",function(){
    window.location.href="findkfc.html";
});
document.querySelector("#logo1").addEventListener("click",function(){
    window.location.href="https://play.google.com/store/apps/details?id=com.yum.kfc";
});
document.querySelector("#logo2").addEventListener("click",function(){
    window.location.href="https://apps.apple.com/in/app/kfc-india/id915824379";
});
document.querySelector("#insta").addEventListener("click",function(){
    window.location.href="https://www.instagram.com/kfcindia_official/";
});
document.querySelector("#facebook").addEventListener("click",function(){
    window.location.href="https://www.facebook.com/KFCIndia";
});
document.querySelector("#twitter").addEventListener("click",function(){
    window.location.href="https://twitter.com/KFC_India";
});